### ISSUE TITLE
OS Error -1073274731 when running README red rectangle example

### ISSUE THREAD

**Issue by 5nyper** [PistonDevelopers/piston#1035]
OS: Windows 10 x64
rustc -V: 1.6.0

Error:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "wglCreateContextAttribsARB failed: OS Error -1073274731 (FormatMessageW() returned error 317) (os error -1073274731)"', ../src/libcore\result.rs:741
Process didn't exit successfully: `target\debug\agar.exe` (exit code: 101)
```

Stack trace:

```
stack backtrace:
   0:           0x92864c - <unknown>
   1:           0x9308ee - <unknown>
   2:           0x8f1f5c - <unknown>
   3:           0x8f26cb - <unknown>
   4:           0x924cc2 - <unknown>
   5:           0x9453d8 - <unknown>
   6:           0x401a0b - <unknown>
   7:           0x401595 - <unknown>
   8:           0x930388 - <unknown>
   9:           0x91b411 - <unknown>
  10:           0x93028d - <unknown>
  11:           0x46edea - <unknown>
  12:           0x4013b4 - <unknown>
  13:           0x4014e7 - <unknown>
  14:     0x7ffe691b8101 - <unknown>
```

:(

**Comment by mitchmindtree** [comment]
```
13:09 < mindtree> vikaton: what project/crate/example did you get this issue in?
13:10 < vikaton> mindtree: Im copying the example on the readme of piston
13:10 < vikaton> the red rectangle
```

I think this is probably more of a `piston_window` issue (or the `gfx_device_gl` backend lib that it uses) as the piston crate itself is backend agnostic, however probably good to leave this here for reference in case other uses run into the same thing before it's fixed.

**Comment by philippotto** [comment]
I'm getting the same error.

**Comment by Grizmoblust** [comment]
It's not just piston, it's also affecting on every game that is written in rust. 

This also infected my own game which is not using piston! It is plain rust-sld2, and nothing else. 
`thread '<main>' panicked at 'called `Option::unwrap()` on a ``None`` value', ../src/libcore/option.rs:330`

The rust dev team must wrote a breaking changes.

**Comment by bvssvni** [comment]
@Vikaton Are you using MSVC? I wonder whether this is related to https://github.com/PistonDevelopers/piston/issues/1032#issuecomment-214674415.

**Comment by bvssvni** [comment]
@Vikaton https://github.com/PistonDevelopers/opengl_graphics/pull/236 fixed a possible dangling pointer. Do you still get the error?

**Comment by Vikaton** [comment]
I updated Rust to 1.9.0 and when I tired running cargo build I got:

```
$ cargo run --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to parse registry's information for: wayland-client

Caused by:
  the given version requirement is invalid
```

**Comment by josephpd3** [comment]
I am having the same issue as @Vikaton

**Comment by stuaxo** [comment]
Just got the same error as  Vikaton, I was on a really old version of rust from 2015 and got the error, then updated and still have it.

**Comment by Kagami** [comment]
Have same error when trying to publish gfx_text:

```
$ cargo publish --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging gfx_text v0.11.0 (file:///home/kagami/code/gfx_text)
   Archiving .gitignore
   Archiving .travis.yml
   Archiving Cargo.toml
   Archiving LICENSE
   Archiving README.md
   Archiving assets/LICENSE.txt
   Archiving assets/NotoSans-Regular.ttf
   Archiving examples/assets/LICENSE.txt
   Archiving examples/assets/Ubuntu-R.ttf
   Archiving examples/styles.rs
   Archiving scripts/id_rsa.enc
   Archiving scripts/travis-doc-upload.cfg
   Archiving src/font.rs
   Archiving src/lib.rs
   Verifying gfx_text v0.11.0 (file:///home/kagami/code/gfx_text)
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to verify package tarball

Caused by:
  failed to parse registry's information for: wayland-client

Caused by:
  the given version requirement is invalid
```

```
$ rustc --version
rustc 1.9.0 (e4e8b6668 2016-05-18)
$ cargo --version
cargo 0.8.0 (built 2016-03-10)
```

Does anyone have solution for this?

**Comment by Kagami** [comment]
Upgrading cargo to 0.9.0 helped in my case.

**Comment by stuaxo** [comment]
Can confirm, upgrading cargo fixed it for me too.

**Comment by bvssvni** [comment]
Closing.
