### ISSUE TITLE
InvalidEnum error

### ISSUE THREAD

**Issue by Bluebird45** [PistonDevelopers/piston#1055]
Hi,
I wonder if someone could offer me some advice. I have compiled and run <b>spinning square</b> but this program, <b>red-square</b>, won't run despite my efforts to resolve the errors.

This is on Debian 8.3 and Rust stable (1.8) under Rustup.

My OpenGL version is 2.1, and so I had to change one line in spinning square to reflect that version.

This is the error I get from "cargo run" on the unmodified code of red-square:

> 
> Running target/debug/red-square
> thread <main> panicked at 'Failed to get root window: XError { description: "GLXBadFBConfig", error_code: 178, request_code: 155, minor_code: 34 }', ../src/libcore/result.rs:746
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> Process didn't exit successfully: `target/debug/red-square` (exit code: 101)
> 

If I modify the code as follows (with the added lines indicated) to downgrade the OpenGL version, then I get the different error message below. 

<pre>
extern crate piston_window;

use piston_window::*;

fn main() {
    let opengl = OpenGL::V2_1;              //added line
    let window: PistonWindow =
        WindowSettings::new("Hello Piston!", [640, 480])
        .opengl(opengl)                     // added line
        .exit_on_esc(true).build().unwrap();
    for e in window {
        e.draw_2d(|c, g| {
            clear([1.0; 4], g);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [0.0, 0.0, 100.0, 100.0],
                      c.transform, g);
        });
    }
}
</pre>

> Running target/debug/red-square
> thread <main> panicked at 'Error after executing command BindProgram(0): InvalidEnum', /home/user/.cargo/registry/src/github.com-88ac128001ac3a9a/gfx_device_gl-0.9.0/src/lib.rs:283
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> Process didn't exit successfully: `target/debug/red-square` (exit code: 101)
> 

EDIT: I'd call this a bug rather than "help wanted." I'm just not sure whether it's a bug in Rust, Piston or OpenGL.

**Comment by Bluebird45** [comment]
I fixed this as follows; it now runs.

<pre>
    extern crate piston_window;
    
    use piston_window::*;
    
    fn main() {
        let mut window: PistonWindow =
            WindowSettings::new("Hello Piston!", [640, 480])
            .exit_on_esc(true).opengl(OpenGL::V2_1).build().unwrap();
    //                        ^^^^^^^^^^^^^^^^^^^^^
    //                             add this only
    //
        while let Some(e) = window.next() {
            window.draw_2d(&e, |c, g| {
                clear([1.0; 4], g);
                rectangle([1.0, 0.0, 0.0, 1.0], // red
                    [0.0, 0.0, 100.0, 100.0],
                    c.transform, g);
            });
        }
    }
</pre>
