### ISSUE TITLE
Issues running piston applications built with MSVC

### ISSUE THREAD

**Issue by kookerus** [PistonDevelopers/piston#1104]
When running a piston application built with MSVC x64, I can get several errors, and sometimes it runs fine.

Some of the errors are as follows:

```
thread '<main>' panicked at 'compile_shader: Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

', C:\Users\Tay\.cargo\git\checkouts\opengl_graphics-fb77cb8da5f0886d\master\src\back_end.rs:140
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
thread '<main>' panicked at 'compile_shader: Vertex shader failed to compile with the following errors:
ERROR: 0:1: error(#132) Syntax error: "P" parse error
ERROR: error(#273) 1 compilation errors.  No code generated

', C:\Users\Tay\.cargo\git\checkouts\opengl_graphics-fb77cb8da5f0886d\master\src\back_end.rs:140
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target\debug\rust-2048.exe` (exit code: 101)
```

```
thread '<main>' panicked at 'compile_shader: Vertex shader failed to compile with the following errors:
ERROR: 0:1: error(#132) Syntax error: "<" parse error
ERROR: error(#273) 1 compilation errors.  No code generated

', C:\Users\Tay\.cargo\git\checkouts\opengl_graphics-fb77cb8da5f0886d\master\src\back_end.rs:140
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target\debug\rust-2048.exe` (exit code: 101)
```

Backtrace:

```
thread '<main>' panicked at 'compile_shader: Vertex shader failed to compile with the following errors:
ERROR: 0:1: error(#132) Syntax error: "<" parse error
ERROR: error(#273) 1 compilation errors.  No code generated

', C:\Users\Tay\.cargo\git\checkouts\opengl_graphics-fb77cb8da5f0886d\master\src\back_end.rs:140
stack backtrace:
   0:     0x7ff73d4e0252 - std::rt::lang_start::hbcefdc316c2fbd45
   1:     0x7ff73d4df83d - std::rt::lang_start::hbcefdc316c2fbd45
   2:     0x7ff73d4d268d - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   3:     0x7ff73d4e25fb - rust_begin_unwind
   4:     0x7ff73d4d370f - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   5:     0x7ff73d39c604 - new
                        at c:\Users\Tay\Downloads\rust-2048\<std macros>:8
   6:     0x7ff73d39d033 - new
                        at C:\Users\Tay\.cargo\git\checkouts\opengl_graphics-fb77cb8da5f0886d\master\src\back_end.rs:226
   7:     0x7ff73d29123f - main
                        at c:\Users\Tay\Downloads\rust-2048\src\main.rs:34
   8:     0x7ff73d4df23c - std::rt::lang_start::hbcefdc316c2fbd45
   9:     0x7ff73d4e4a41 - _rust_maybe_catch_panic
  10:     0x7ff73d4def74 - std::rt::lang_start::hbcefdc316c2fbd45
  11:     0x7ff73d2be089 - main
  12:     0x7ff73d4efee8 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  13:     0x7ffd55cc8101 - BaseThreadInitThunk
error: Process didn't exit successfully: `target\debug\rust-2048.exe` (exit code: 101)
```

**Comment by kookerus** [comment]
I got a gnu toolchain with MSYS2 set up on the same Windows box, and I still get the same issue, so it isn't just the MSVC toolchain.

**Comment by kookerus** [comment]
Apparently the issue was a part of the specific project I was building, not Piston. My bad.
