### ISSUE TITLE
wl_display@1: error 1: invalid method 9 (since 3 < 4), object wl_surface@26

### ISSUE THREAD

**Issue by afonso360** [PistonDevelopers/piston#1137]
Hi,

When trying out the example on the piston.rs page, the application panics soon after starting with the following backtrace:

    wl_display@1: error 1: invalid method 9 (since 3 < 4), object wl_surface@26
    thread 'main' panicked at 'Wayland connection unexpectedly lost: Error { repr: Os { code: 22, message: "Invalid argument" } }', ../src/libcore/result.rs:837
    stack backtrace:
       1:     0x56422212ffea - std::sys::imp::backtrace::tracing::imp::write::h944c02ac40aee2d7
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
       2:     0x56422213289f - std::panicking::default_hook::{{closure}}::h6875a2976258b020
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
       3:     0x56422213249e - std::panicking::default_hook::h88ffbc5922643264
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
       4:     0x564222132d47 - std::panicking::rust_panic_with_hook::ha5aed1dfc0e220e3
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
       5:     0x564222132bd4 - std::panicking::begin_panic::hc066339e2fdc17d1
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
       6:     0x564222132af9 - std::panicking::begin_panic_fmt::h5912b2d2df332044
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
       7:     0x564222132a87 - rust_begin_unwind
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
       8:     0x56422216e1ed - core::panicking::panic_fmt::h561c5ee168a3d2cb
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
       9:     0x564222054e5e - core::result::unwrap_failed::h8444106f15d6bc67
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
      10:     0x564222047bc7 - <core::result::Result<T, E>>::expect::h9e2fc2fa5aaa5f96
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:761
      11:     0x564222069c43 - winit::api::wayland::context::WaylandContext::dispatch_pending::haf08cd74a55da65f
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.5.6/src/api/wayland/context.rs:229
      12:     0x56422206faf0 - winit::api::wayland::window::Window::next_event::hadb5fcdfe8b13535
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.5.6/src/api/wayland/window.rs:151
      13:     0x56422206eb90 - <winit::api::wayland::window::PollEventsIterator<'a> as core::iter::iterator::Iterator>::next::hb542ddad34d7c3ff
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.5.6/src/api/wayland/window.rs:47
      14:     0x564221fffc40 - <winit::platform::platform::api_dispatch::PollEventsIterator<'a> as core::iter::iterator::Iterator>::next::hfe24380692e7b9cf
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.5.6/src/platform/linux/api_dispatch.rs:142
      15:     0x56422201228b - <winit::window::PollEventsIterator<'a> as core::iter::iterator::Iterator>::next::h183bd0aac1186b76
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.5.6/src/window.rs:384
      16:     0x56422201c42e - <glutin::platform::platform::wayland::PollEventsIterator<'a> as core::iter::iterator::Iterator>::next::hfd7eb857fd3fc81e
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.0/src/platform/linux/wayland.rs:43
      17:     0x564221f29050 - <glutin::platform::platform::api_dispatch::PollEventsIterator<'a> as core::iter::iterator::Iterator>::next::h666ed69debd3bd82
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.0/src/platform/linux/api_dispatch.rs:64
      18:     0x564221f67dab - <glutin::window::PollEventsIterator<'a> as core::iter::iterator::Iterator>::next::h57507e6afad8ae9f
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.0/src/window.rs:252
      19:     0x564221f69782 - glutin_window::GlutinWindow::poll_event::ha1312952a2079159
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.33.0/src/lib.rs:215
      20:     0x564221f6ad6b - <glutin_window::GlutinWindow as window::Window>::poll_event::h91add6f54646e4b8
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.33.0/src/lib.rs:355
      21:     0x564221ebc90b - event_loop::WindowEvents::next::h16a6444c9c8cb635
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-event_loop-0.27.0/src/lib.rs:274
      22:     0x564221ecf7d6 - <piston_window::PistonWindow<W>>::next::hdb13dd7a493d2590
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/piston_window-0.59.0/src/lib.rs:245
      23:     0x564221f2762c - _3ds::main::h6882e3d56b35b6da
                            at /home/afonso/git/3DS/src/main.rs:9
      24:     0x56422213b77a - __rust_maybe_catch_panic
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
      25:     0x56422213358a - std::rt::lang_start::h5d71a3afaaa4b2ff
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
      26:     0x564221f27b12 - main
      27:     0x7f48a896b400 - __libc_start_main
      28:     0x564221eba769 - _start
      29:                0x0 - <unknown>
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:837
    stack backtrace:
       1:     0x56422212ffea - std::sys::imp::backtrace::tracing::imp::write::h944c02ac40aee2d7
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
       2:     0x56422213289f - std::panicking::default_hook::{{closure}}::h6875a2976258b020
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
       3:     0x56422213249e - std::panicking::default_hook::h88ffbc5922643264
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
       4:     0x564222132d47 - std::panicking::rust_panic_with_hook::ha5aed1dfc0e220e3
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
       5:     0x564222132bd4 - std::panicking::begin_panic::hc066339e2fdc17d1
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
       6:     0x564222132af9 - std::panicking::begin_panic_fmt::h5912b2d2df332044
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
       7:     0x564222132a87 - rust_begin_unwind
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
       8:     0x56422216e1ed - core::panicking::panic_fmt::h561c5ee168a3d2cb
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
       9:     0x564222054b1e - core::result::unwrap_failed::h6941460c434bef82
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
      10:     0x564222048a00 - <core::result::Result<T, E>>::unwrap::hc059e48b79dd85d9
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:737
      11:     0x56422206a708 - winit::api::wayland::context::WaylandContext::prune_dead_windows::hfdff852e092a4038
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.5.6/src/api/wayland/context.rs:274
      12:     0x56422207034f - <winit::api::wayland::window::Window as core::ops::Drop>::drop::h4ca5a208aa623d16
                            at /home/afonso/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.5.6/src/api/wayland/window.rs:296
      13:     0x564221eddd20 - drop::ha592b2843560d78c
      14:     0x564221edc2e7 - drop::h35c1c39ac1cbc6d3
      15:     0x564221ede198 - drop::hb907c7e16af4cffc
      16:     0x564221edc080 - drop::h256b71a974cbd32c
      17:     0x564221edc278 - drop::h319ad263542ce8b0
      18:     0x564221edebd0 - drop::hf927ccbbb58dad3b
      19:     0x564221edc590 - drop::h3bc4389538c45eb2
      20:     0x564221f277c1 - _3ds::main::h6882e3d56b35b6da
                            at /home/afonso/git/3DS/src/main.rs:17
      21:     0x56422213b77a - __rust_maybe_catch_panic
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
      22:     0x56422213358a - std::rt::lang_start::h5d71a3afaaa4b2ff
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                            at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
      23:     0x564221f27b12 - main
      24:     0x7f48a896b400 - __libc_start_main
      25:     0x564221eba769 - _start
      26:                0x0 - <unknown>
    thread panicked while panicking. aborting.

The problem seems to be from me using wayland.

This also happens in the spinning square and all the examples in the piston-examples repository.

Here are my settings 
`piston = "0.27.0"`
`piston_window = "0.59.0"`

rustc --version
`rustc 1.15.0-nightly (d5814b03e 2016-11-23)`
cargo --version
`cargo 0.16.0-nightly (d1bfc01 2016-11-18)`

Fedora 25
GNOME Shell 3.22.2

**Comment by afonso360** [comment]
The problem is actually in winit and there is already an issue filed in there.

https://github.com/tomaka/winit/issues/97
