### ISSUE TITLE
all_piston_window example panic on exit

### ISSUE THREAD

**Issue by blep** [PistonDevelopers/piston#1179]
Environment:
```
rustup show
Default host: x86_64-pc-windows-msvc

stable-x86_64-pc-windows-msvc (default)
rustc 1.17.0 (56124baa9 2017-04-24)
```

Panic traceback:
```
d:\prg\prj\rust\conrod>cargo run --release --features "piston" --example all_piston_window
    Finished release [optimized] target(s) in 0.0 secs
     Running `target\release\examples\all_piston_window.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 6, message: "The handle is invalid." } })', src\libcore\result.rs:859
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: piston_window::create_main_targets
   9: <glutin_window::GlutinWindow as window::OpenGLWindow>::make_current
  10: __STATIC_FMTSTR
  11: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  12: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  13: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  14: BaseThreadInitThunk
error: process didn't exit successfully: `target\release\examples\all_piston_window.exe` (exit code: 101)

```

Dependencies: (recently checkouted conrod from github)

```

[root]
name = "conrod"
version = "0.52.0"
dependencies = [
 "daggy 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "find_folder 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "fnv 1.0.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "gfx 0.15.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "gfx_core 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "gfx_window_glutin 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "glium 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "glutin 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "image 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "num 0.1.37 (registry+https://github.com/rust-lang/crates.io-index)",
 "piston2d-graphics 0.21.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "piston_window 0.65.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "pistoncore-input 0.18.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand 0.3.15 (registry+https://github.com/rust-lang/crates.io-index)",
 "rusttype 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "winit 0.5.11 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

**Comment by blep** [comment]
Sorry wrong project I think (was a conrod issue with pyston)
