### ISSUE TITLE
"Couldn't find any pixel format that matches the criterias": native Ubuntu on modern computer

### ISSUE THREAD

**Issue by rivertam** [PistonDevelopers/piston#1205]
So I'm sorry if I've missed something, but I've seen this error only in the context of VirtualBox. However, I'm running the program on a ThinkPad X1 Carbon with Ubuntu as the native OS. My OpenGL version is 3.0, which I think is new enough to support the default settings? I'm not totally sure, but it seems like people are having issues only if they can't support 2.1.

My code is identical to the code in the README (I copy-pasted it), so I won't replicate it here. My error message is as follows:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn\'t find any pixel fo
rmat that matches the criterias."', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:31
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: arrrr::main
             at src/main.rs:7
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  14: main
  15: __libc_start_main
  16: _start
```

I looked through the FAQ and all the issues I saw when I Googled the issue, but I still feel as though I'm making a nooby mistake rather than there being an actual bug in Piston. Does anyone have any insight?

Thanks!

**Comment by rivertam** [comment]
My apologies, I think this is a duplicate of https://github.com/PistonDevelopers/piston/issues/1202, so I will close this unless someone thinks it's unique.
